// Code generated by MockGen. DO NOT EDIT.
// Source: internal/sync.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	identitystore "github.com/aws/aws-sdk-go-v2/service/identitystore"
	gomock "github.com/golang/mock/gomock"
)

// MockSyncGSuite is a mock of SyncGSuite interface.
type MockSyncGSuite struct {
	ctrl     *gomock.Controller
	recorder *MockSyncGSuiteMockRecorder
}

// MockSyncGSuiteMockRecorder is the mock recorder for MockSyncGSuite.
type MockSyncGSuiteMockRecorder struct {
	mock *MockSyncGSuite
}

// NewMockSyncGSuite creates a new mock instance.
func NewMockSyncGSuite(ctrl *gomock.Controller) *MockSyncGSuite {
	mock := &MockSyncGSuite{ctrl: ctrl}
	mock.recorder = &MockSyncGSuiteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncGSuite) EXPECT() *MockSyncGSuiteMockRecorder {
	return m.recorder
}

// SyncGroups mocks base method.
func (m *MockSyncGSuite) SyncGroups(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGroups", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncGroups indicates an expected call of SyncGroups.
func (mr *MockSyncGSuiteMockRecorder) SyncGroups(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGroups", reflect.TypeOf((*MockSyncGSuite)(nil).SyncGroups), arg0)
}

// SyncGroupsUsers mocks base method.
func (m *MockSyncGSuite) SyncGroupsUsers(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncGroupsUsers", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncGroupsUsers indicates an expected call of SyncGroupsUsers.
func (mr *MockSyncGSuiteMockRecorder) SyncGroupsUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncGroupsUsers", reflect.TypeOf((*MockSyncGSuite)(nil).SyncGroupsUsers), arg0, arg1)
}

// SyncUsers mocks base method.
func (m *MockSyncGSuite) SyncUsers(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUsers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncUsers indicates an expected call of SyncUsers.
func (mr *MockSyncGSuiteMockRecorder) SyncUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUsers", reflect.TypeOf((*MockSyncGSuite)(nil).SyncUsers), arg0)
}

// MockIdentityStoreAPI is a mock of IdentityStoreAPI interface.
type MockIdentityStoreAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityStoreAPIMockRecorder
}

// MockIdentityStoreAPIMockRecorder is the mock recorder for MockIdentityStoreAPI.
type MockIdentityStoreAPIMockRecorder struct {
	mock *MockIdentityStoreAPI
}

// NewMockIdentityStoreAPI creates a new mock instance.
func NewMockIdentityStoreAPI(ctrl *gomock.Controller) *MockIdentityStoreAPI {
	mock := &MockIdentityStoreAPI{ctrl: ctrl}
	mock.recorder = &MockIdentityStoreAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdentityStoreAPI) EXPECT() *MockIdentityStoreAPIMockRecorder {
	return m.recorder
}

// CreateGroup mocks base method.
func (m *MockIdentityStoreAPI) CreateGroup(ctx context.Context, params *identitystore.CreateGroupInput, optFns ...func(*identitystore.Options)) (*identitystore.CreateGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateGroup", varargs...)
	ret0, _ := ret[0].(*identitystore.CreateGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockIdentityStoreAPIMockRecorder) CreateGroup(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockIdentityStoreAPI)(nil).CreateGroup), varargs...)
}

// CreateGroupMembership mocks base method.
func (m *MockIdentityStoreAPI) CreateGroupMembership(ctx context.Context, params *identitystore.CreateGroupMembershipInput, optFns ...func(*identitystore.Options)) (*identitystore.CreateGroupMembershipOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateGroupMembership", varargs...)
	ret0, _ := ret[0].(*identitystore.CreateGroupMembershipOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroupMembership indicates an expected call of CreateGroupMembership.
func (mr *MockIdentityStoreAPIMockRecorder) CreateGroupMembership(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroupMembership", reflect.TypeOf((*MockIdentityStoreAPI)(nil).CreateGroupMembership), varargs...)
}

// DeleteGroup mocks base method.
func (m *MockIdentityStoreAPI) DeleteGroup(ctx context.Context, params *identitystore.DeleteGroupInput, optFns ...func(*identitystore.Options)) (*identitystore.DeleteGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteGroup", varargs...)
	ret0, _ := ret[0].(*identitystore.DeleteGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockIdentityStoreAPIMockRecorder) DeleteGroup(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockIdentityStoreAPI)(nil).DeleteGroup), varargs...)
}

// DeleteGroupMembership mocks base method.
func (m *MockIdentityStoreAPI) DeleteGroupMembership(ctx context.Context, params *identitystore.DeleteGroupMembershipInput, optFns ...func(*identitystore.Options)) (*identitystore.DeleteGroupMembershipOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteGroupMembership", varargs...)
	ret0, _ := ret[0].(*identitystore.DeleteGroupMembershipOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteGroupMembership indicates an expected call of DeleteGroupMembership.
func (mr *MockIdentityStoreAPIMockRecorder) DeleteGroupMembership(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupMembership", reflect.TypeOf((*MockIdentityStoreAPI)(nil).DeleteGroupMembership), varargs...)
}

// DeleteUser mocks base method.
func (m *MockIdentityStoreAPI) DeleteUser(ctx context.Context, params *identitystore.DeleteUserInput, optFns ...func(*identitystore.Options)) (*identitystore.DeleteUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUser", varargs...)
	ret0, _ := ret[0].(*identitystore.DeleteUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIdentityStoreAPIMockRecorder) DeleteUser(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIdentityStoreAPI)(nil).DeleteUser), varargs...)
}

// GetGroupMembershipId mocks base method.
func (m *MockIdentityStoreAPI) GetGroupMembershipId(ctx context.Context, params *identitystore.GetGroupMembershipIdInput, optFns ...func(*identitystore.Options)) (*identitystore.GetGroupMembershipIdOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGroupMembershipId", varargs...)
	ret0, _ := ret[0].(*identitystore.GetGroupMembershipIdOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMembershipId indicates an expected call of GetGroupMembershipId.
func (mr *MockIdentityStoreAPIMockRecorder) GetGroupMembershipId(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembershipId", reflect.TypeOf((*MockIdentityStoreAPI)(nil).GetGroupMembershipId), varargs...)
}

// IsMemberInGroups mocks base method.
func (m *MockIdentityStoreAPI) IsMemberInGroups(ctx context.Context, params *identitystore.IsMemberInGroupsInput, optFns ...func(*identitystore.Options)) (*identitystore.IsMemberInGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "IsMemberInGroups", varargs...)
	ret0, _ := ret[0].(*identitystore.IsMemberInGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMemberInGroups indicates an expected call of IsMemberInGroups.
func (mr *MockIdentityStoreAPIMockRecorder) IsMemberInGroups(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMemberInGroups", reflect.TypeOf((*MockIdentityStoreAPI)(nil).IsMemberInGroups), varargs...)
}

// ListGroupMemberships mocks base method.
func (m *MockIdentityStoreAPI) ListGroupMemberships(ctx context.Context, params *identitystore.ListGroupMembershipsInput, optFns ...func(*identitystore.Options)) (*identitystore.ListGroupMembershipsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGroupMemberships", varargs...)
	ret0, _ := ret[0].(*identitystore.ListGroupMembershipsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupMemberships indicates an expected call of ListGroupMemberships.
func (mr *MockIdentityStoreAPIMockRecorder) ListGroupMemberships(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupMemberships", reflect.TypeOf((*MockIdentityStoreAPI)(nil).ListGroupMemberships), varargs...)
}

// ListGroups mocks base method.
func (m *MockIdentityStoreAPI) ListGroups(ctx context.Context, params *identitystore.ListGroupsInput, optFns ...func(*identitystore.Options)) (*identitystore.ListGroupsOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGroups", varargs...)
	ret0, _ := ret[0].(*identitystore.ListGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockIdentityStoreAPIMockRecorder) ListGroups(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockIdentityStoreAPI)(nil).ListGroups), varargs...)
}

// ListUsers mocks base method.
func (m *MockIdentityStoreAPI) ListUsers(ctx context.Context, params *identitystore.ListUsersInput, optFns ...func(*identitystore.Options)) (*identitystore.ListUsersOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListUsers", varargs...)
	ret0, _ := ret[0].(*identitystore.ListUsersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockIdentityStoreAPIMockRecorder) ListUsers(ctx, params interface{}, optFns ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockIdentityStoreAPI)(nil).ListUsers), varargs...)
}
